# Generated by Django 3.0.8 on 2020-07-14 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(blank=True, null=True)),
                ('cancelado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=60)),
                ('nomereduzido', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=60)),
                ('complemento', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('telefone1', models.CharField(max_length=11)),
                ('telefone2', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(max_length=45)),
                ('genero', models.CharField(max_length=45)),
                ('ativo', models.CharField(max_length=1)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(blank=True, null=True)),
                ('cancelado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(blank=True, null=True)),
                ('cancelado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(blank=True, null=True)),
                ('cancelado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa_Vinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(blank=True, null=True)),
                ('cancelado', models.CharField(max_length=1)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_vinculo', to='core.Pessoa')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_pessoa', to='core.Vinculo')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa_Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(blank=True, null=True)),
                ('cancelado', models.CharField(max_length=1)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividade_pessoa', to='core.Atividade')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_atividade', to='core.Pessoa')),
            ],
        ),
    ]
